### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#37] opened 2016-08-02 23:43 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** No have force type, and don't work without it

Thanks

**Comment by Irian81** [comment] 2023-11-20 22:21
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:21 UTC
