### ISSUE TITLE
[Anon] Bug report: The_Undead.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#54] opened 2017-04-17 07:33 UTC
**File:** The_Undead.catz

**BattleScribe version:** 2.00.33

**Platform:** Android

**Dropbox:** No

**Description:** I downloaded the Mordheim Giles last weeks, at first open i created an Undead warband. I the closed battlescribe.
After some minutes i opened It again, i wanted to change some stuff. As i clicked in the list appeared a warning message, that some of the data files were no longer valid. I pressed ok ti continue, and i found that all the list was blank. 
I tryed to create a new Undead warband, but as i select "Undead" warband in the creation of the roster, the It become all blank, no options available, no characters shown.
I tryed to cancel all the "mordheim" data from the program, download It again and repeat, but still i see nothing inside the Undead roster

**Comment by Irian81** [comment] 2023-11-23 16:30
Tried to reproduce this but I can work well enough with the undeads, will give the data file an overhaul either way since I'm trying to bring them all to the same level, will close this for now since it's also quite old.

**Closed by Irian81** 2023-11-23 16:30 UTC
