### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#34] opened 2016-07-02 21:57 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** When you are adding a force during the roster creation process, you can't select anything in the "Force type" category and it stops you from adding the force at all since this is a required field to fill. Furthermore, you constantly get the error message telling that you have a data file that requires a newer version of BattleScribe, but I have the lastest one.

**Comment by Irian81** [comment] 2023-11-20 22:20
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:20 UTC
