### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#30] opened 2016-06-13 17:42 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** The Mordheim data has no option for a Force Type and as such I cannot make a single list using the above repository.

**Comment by Irian81** [comment] 2023-11-20 22:17
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:17 UTC
