### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#40] opened 2016-09-03 08:23 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** Cannot select force type (no drop down menu) when trying to create roster, says 'must select a catalogue and a force type'

**Comment by Irian81** [comment] 2023-11-20 22:22
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:22 UTC
