### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#35] opened 2016-07-17 05:56 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Trying to create a warband and the app crashes, the rest of datafiles work perfectly

**Comment by Irian81** [comment] 2023-11-20 22:20
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:20 UTC
