### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#43] opened 2016-10-05 22:43 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.09

**Platform:** Android

**Dropbox:** No

**Description:** I am unable to create a warband roster.  But when I try to add a force it will not allow me to choose a force and a catalog. I can choose my catalog option but when it comes to the force tab nothing appears.

**Comment by gandalf78** [comment] 2022-11-10 18:54
Have you updated the program to the last version? Try again and please report here if you have any other issues

**Comment by Irian81** [comment] 2023-11-20 22:10
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:10 UTC
