### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#46] opened 2016-10-19 22:08 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.09

**Platform:** Android

**Dropbox:** Yes

**Description:** Creating a new roster the "force type" slot is empty and without options.
The creation of the roster can't go forward from this point.
Thank you ;)

**Comment by gandalf78** [comment] 2022-11-10 18:56
Try again with the last version of the program. Thanks

**Comment by Irian81** [comment] 2023-11-20 22:22
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:22 UTC
