### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#55] opened 2017-07-28 15:53 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.10

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When using Mordheim v14 I have found the app crashes each time I try to make a roster.

**Comment by Irian81** [comment] 2023-11-21 08:17
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-21 08:17 UTC
