### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#32] opened 2016-06-23 23:59 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** No force type drop-down box after selecting to add a force.

**Comment by Irian81** [comment] 2023-11-20 22:18
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:18 UTC
