### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#44] opened 2016-10-09 02:31 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.10

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Any time I try to open the war band link the app crashes. I've updated everything and nothing is working. Verified version similarity with friends phone that works.

**Comment by gandalf78** [comment] 2022-11-10 18:55
Try again with the last version of Battlescribe!

**Comment by Irian81** [comment] 2023-11-20 22:10
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:10 UTC
