### ISSUE TITLE
[Anon] Bug report: Dwarven_Tresure_Hunters.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#31] opened 2016-06-22 01:08 UTC
**File:** Dwarven_Tresure_Hunters.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** The list itself does'nt load when I try to create a new warband. There is no choises at all, like  blank screen. Me and my friends tried it on PC and non of them work. We both are on V18 and with 1.15.07.

On my Android BattleScribe v1.15.07
I have V17 and all work well, I can select and create everything. It work flawless!

**Comment by Irian81** [comment] 2023-11-20 22:18
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:18 UTC
