### ISSUE TITLE
[Anon] Bug report: Ork_Mob.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#50] opened 2016-12-28 22:27 UTC
**File:** Ork_Mob.catz

**BattleScribe version:** 2.00.21

**Platform:** Android

**Dropbox:** No

**Description:** Goblins cost 15 and soul coste 10 points. Also not updated to 2.0 so it bugs and the roser appears empty.

**Comment by gandalf78** [comment] 2022-11-10 19:00
Please try again using the last version of the app. let us know, thanks.

**Comment by Irian81** [comment] 2023-11-21 08:08
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed** 2023-11-25 16:41 UTC
