### ISSUE TITLE
[Anon] Bug report: Dwarven_Tresure_Hunters.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#36] opened 2016-07-30 15:08 UTC
**File:** Dwarven_Tresure_Hunters.catz

**BattleScribe version:** 1.14.07

**Platform:** Android

**Dropbox:** No

**Description:** I can select the Warband (Dwarf) but the there is nothing more cant select Heroes or Henchmen or anything else (only whitescreen).

**Comment by Irian81** [comment] 2023-11-21 08:08
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-21 08:08 UTC
