### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#47] opened 2016-10-26 23:20 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.14.07

**Platform:** Android

**Dropbox:** Yes

**Description:** Won't let you make a roster as it says needs force type which is not available

**Comment by gandalf78** [comment] 2022-11-10 18:58
Have you downloaded the last version of the app? Try again and let us know.

**Comment by Irian81** [comment] 2023-11-20 22:16
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:16 UTC
