### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#38] opened 2016-08-26 19:36 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** When trying to build a mordhiem warband,  during the creation step - I can pick my parent force and catalog but I cannot pick force type. When I hit "ok" to create my warband I get the error message, "you must select both a catalog and force type. I cannot select force type because that option is not available to change and this prevents me from making a force of any type

**Comment by Irian81** [comment] 2023-11-20 22:21
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:21 UTC
