### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#45] opened 2016-10-12 19:46 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.09

**Platform:** Android

**Dropbox:** No

**Description:** I tried to create a warband after downloading and opening the index
bsi file with battlescribe. 

When I add a Mordheim v14 force the Parent Force field is greyed out, Force type is completely blank (although the catalogue works as expected). I am unable to create a new force ("you must select both a catalogue and a force type"), regardless of which race I select.

**Comment by gandalf78** [comment] 2022-11-10 18:56
Try with the last version of Battlescribe program.

**Comment by Irian81** [comment] 2023-11-20 22:08
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:08 UTC
