### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#39] opened 2016-08-30 10:53 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** When adding a force in a Mordheim roster I can't select a force type, so I can't add any force.

**Comment by Irian81** [comment] 2023-11-20 22:21
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:21 UTC
