### ISSUE TITLE
[Anon] Bug report: Mordheim.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#29] opened 2016-06-09 12:04 UTC
**File:** Mordheim.gstz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Keeps crashing when you select mordheim in the drop box

**Comment by Irian81** [comment] 2023-11-20 22:17
Closing issue it's 7 years old already and cannot reproduce on recent systems.

**Closed by Irian81** 2023-11-20 22:17 UTC
